config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", :as => :rails_health_check

  devise_for :users
  root "pages#home"
  get "protected" => "pages#protected"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name terms_and_conditions])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[full_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def protected
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orange Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application', data: { "turbo-track": "reload" } %>
    <%= vite_javascript_tag 'application' %>
  </head>

  <body>
    <%= render partial: "shared/notifications", locals: { notice: notice, alert: alert } %>

    <%= yield %>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-50">
  <head>
    <title>Orange Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application', data: { "turbo-track": "reload" } %>
    <%= vite_javascript_tag 'application' %>
  </head>

  <body class="h-full">
    <%= render partial: "shared/notifications", locals: { message: notice || alert } %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex justify-center items-center w-screen h-screen text-center" data-controller="hello">
  <div class="flex flex-col items-center">
    <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Starting your project fast with <span class="underline underline-offset-3 decoration-8 decoration-amber-500 dark:decoration-amber-600">Orange Starter</span></h1>
    <p class="flex gap-2 mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">Edit this page in<span class="inline-flex items-center px-2.5 py-0.5 text-xs font-medium text-gray-800 bg-gray-100 rounded border border-gray-500 me-2 dark:bg-gray-700 dark:text-gray-400">/app/views/pages/home.html.erb</span></p>

    <div class="mt-6">
      <% if current_user %>
        <p class="mb-2">Hello, <%= current_user.email %></p>
        <%= link_to "Logout", destroy_user_session_path, class: "inline-flex justify-center items-center px-5 py-3 text-base font-medium text-center text-white bg-amber-500 rounded-lg hover:bg-amber-600 focus:ring-4 focus:ring-amber-300 dark:focus:ring-amber-600", data: { turbo_method: :delete } %>
      <% else %>
        <div class="flex gap-4">
          <%= link_to "Login", new_user_session_path, class: "inline-flex justify-center items-center px-5 py-3 text-base font-medium text-center text-white bg-amber-500 rounded-lg hover:bg-amber-600 focus:ring-4 focus:ring-amber-300 dark:focus:ring-amber-600" %>
          <%= link_to "Sign up", new_user_registration_path, class: "inline-flex justify-center items-center px-5 py-3 text-base font-medium text-center text-white bg-amber-500 rounded-lg hover:bg-amber-600 focus:ring-4 focus:ring-amber-300 dark:focus:ring-amber-600" %>
        </div>
      <% end %>
    </div>

    <% if current_user %>
      <%= link_to protected_path, class: "inline-flex justify-center items-center px-5 py-3 mt-6 text-base font-medium text-center text-white bg-amber-500 rounded-lg hover:bg-amber-600 focus:ring-4 focus:ring-amber-300 dark:focus:ring-amber-600" do %>
        Proctected Page
        <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
        </svg>
      <% end %>
    <% end %>
  </div>

</div>

app/views/pages/protected.html.erb
<div class="flex justify-center items-center w-screen h-screen text-center" data-controller="hello">
  <div class="flex flex-col items-center">
    <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white"><span class="underline underline-offset-3 decoration-8 decoration-amber-500 dark:decoration-amber-600">Protected</span> page!</h1>

    <%= link_to root_path, class: "inline-flex justify-center items-center px-5 py-3 mt-6 text-base font-medium text-center text-white bg-amber-500 rounded-lg hover:bg-amber-600 focus:ring-4 focus:ring-amber-300 dark:focus:ring-amber-600" do %>
      <svg class="w-3.5 h-3.5 rotate-180 me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
      </svg>
      Back
    <% end %>
  </div>
</div>

app/views/shared/_notifications.html.erb
<% if alert %>
  <div class="flex justify-center w-full">
    <div id="toast" 
    class="flex absolute top-10 items-center p-4 mb-4 text-red-800 bg-red-50 rounded-lg dark:bg-gray-800 dark:text-red-400" 
    role="alert" 
    data-controller="notifications"
    data-notification-delay-value="3500"
    data-transition-enter-active="transition ease-out duration-300"
    data-transition-enter-from="transform opacity-0 scale-95"
    data-transition-enter-to="transform opacity-100 scale-100"
    data-transition-leave-active="transition ease-in duration-300"
    data-transition-leave-from="transform opacity-100 scale-100"
    data-transition-leave-to="transform opacity-0 scale-95"
    >
      <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
      </svg>
      <span class="sr-only">Info</span>
      <div class="text-sm font-medium ms-3">
        <%= alert %>
      </div>
      <button type="button" data-action="notifications#hide" class="inline-flex justify-center items-center p-1.5 -mx-1.5 -my-1.5 w-8 h-8 text-red-500 bg-red-50 rounded-lg ms-auto focus:ring-2 focus:ring-red-400 hover:bg-red-200 dark:bg-gray-800 dark:text-red-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-2" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
      </button>
    </div>
  </div>
<% end %>

<% if notice %>
  <div class="flex justify-center w-full">
    <div id="toast" 
    class="flex absolute top-10 items-center p-4 mb-4 text-blue-800 bg-blue-50 rounded-lg dark:bg-gray-800 dark:text-blue-400" 
    role="alert" 
    data-controller="notifications"
    data-notification-delay-value="2000"
    data-transition-enter-active="transition ease-out duration-300"
    data-transition-enter-from="transform opacity-0 scale-95"
    data-transition-enter-to="transform opacity-100 scale-100"
    data-transition-leave-active="transition ease-in duration-300"
    data-transition-leave-from="transform opacity-100 scale-100"
    data-transition-leave-to="transform opacity-0 scale-95"
    >
      <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
      </svg>
      <span class="sr-only">Info</span>
      <div class="block pr-4 text-sm font-medium ms-3">
        <%= notice %>
      </div>
      <button type="button" data-action="notifications#hide" class="inline-flex justify-center items-center p-1.5 -mx-1.5 -my-1.5 w-8 h-8 text-blue-500 bg-blue-50 rounded-lg focus:ring-2 focus:ring-blue-400 hover:bg-blue-200" data-dismiss-target="#alert-2" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
      </button>
    </div>
  </div>
<% end %>